<div class="article_content clearfix" id="article_content">
<link href="style.css" rel="stylesheet"/>
<div class="htmledit_views" id="content_views">
<p><a class="link-info has-card" href="https://blog.csdn.net/chenlycly/article/details/124272585" title="VC++常用功能开发汇总（专栏文章列表，欢迎订阅，持续更新...）"><span class="link-card-box"><span class="link-title">VC++常用功能开发汇总（专栏文章列表，欢迎订阅，持续更新...）</span><span class="link-link"><img alt="" class="link-link-icon" src="image\icon-default.png"/>https://blog.csdn.net/chenlycly/article/details/124272585</span></span></a>       在C/C++的代码中，为了防止代码块执行的过程中产生异常导致软件崩溃，我们会给代码块添加__try...__except或try...catch保护，防止软件因为操作内部触发的异常产生崩溃。本文简单地介绍一下这两种异常捕获的使用示例。</p>
<h2>1、概述</h2>
<p>       当软件运行过程中代码抛出异常，如果异常没有处理，且异常不可自动恢复，会导致软件崩溃闪退。C/C++中提供了异常保护机制，可以捕获到异常并处理掉，这样软件不会因为一些操作的内部错误而产生崩溃，软件可以正常的运行下去。</p>
<p>       C语言中提供了SEH结构化异常捕获<span style="color:#be191c;">__try...__except</span>，C&amp;</p>
</div>
</div>